import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider,Box } from '@chakra-ui/react'
import { Providers } from './providers'
import  Footer from "@/components/Footer/Footer";
import  Navbar from "@/components/Navbar/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TaskBaz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
{/* <link rel="shortcut icon" href="/Frame 39313.png" /> */}
<link rel="icon" href="https://cdn.builder.io/api/v1/image/assets/TEMP/18bac309c301db4b6398c55bf181ba6ba3a58be85b910ed323518266187a3b7c?" type="image/png" sizes="32x32" />
      <body style={{padding:"20px"}} className={inter.className}>
      <Providers>
        
        <Navbar/>
   
        
        {children}
        
        <Footer/>
      </Providers>
        </body>
    </html>
  );
}
